export const homeObjOne = {
  image: require('../../images/sv1.svg').default,
  // id: 'about',
  lightBG: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'topline1',
  headLine: 'headline1',
  description: 'description1',
  buttonLable: 'buttonLable1',
  button: 'projects',
  imgStart: false,
  alt: 'Design',
  dark: false,
  primary: false,
  darkText: true,
  // topHight: true,
  // lowHight: false,
};

export const homeObjTwo = {
  image: require('../../images/sv3.svg').default,
  // id: 'about',
  lightBG: false,
  // lightText: true,
  // lightTextDesc: true,
  topLine: 'topline2',
  headLine: 'headline2',
  description: 'description2',
  buttonLable: 'buttonLable2',
  button: 'services',
  imgStart: true,
  alt: 'Design',
  dark: false,
  primary: true,
  darkText: false,
  // lowHight: true,
  // topHight: false,
};

export const homeObjThree = {
  image: require('../../images/sv2.svg').default,
  // id: 'about',
  lightBG: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'topline3',
  headLine: 'headline1',
  description: 'description3',
  buttonLable: 'buttonLable3',
  button: 'contact',
  imgStart: false,
  alt: 'Design',
  dark: false,
  primary: false,
  darkText: true,
};
